### ISSUE TITLE
Unable to invoke http call

### ISSUE THREAD

**Issue by Dineshrajaa** [razorpay/razorpay-cordova-sample-app#10]
Hi all,

I am trying to hit an API endpoint to verify Payment in the success call back of RazorPayCheckout but it is not happening still alert with paymentid is coming correctly.

is there any workaround to resolve this issue??

PS:
I am developing the app in Ionic3

**Comment by hariramsvnit** [comment]
@Dineshrajaa The issue is not related to Razorpay Cordova plugin, you may find the solution to your issue over StackOverflow.
