### ISSUE TITLE
RazorpayCheckout is not defined.

### ISSUE THREAD

**Issue by VigneshSAN** [razorpay/razorpay-cordova-sample-app#12]
Actually, I downloaded your code and run the Ionic 3 razor pay example and also install the Razorpay plugin. But, while running the project it shows me an error like RazorpayCheckout is not defined. Kindly help me to solve the issue.

`Runtime Error
RazorpayCheckout is not defined
Stack
ReferenceError: RazorpayCheckout is not defined
    at HomePage.webpackJsonp.191.HomePage.pay (http://localhost:8100/build/main.js:73:9)
    at Object.eval [as handleEvent] (ng:///AppModule/HomePage.ngfactory.js:163:24)
    at handleEvent (http://localhost:8100/build/vendor.js:12273:138)
    at callWithDebugContext (http://localhost:8100/build/vendor.js:13565:42)
    at Object.debugHandleEvent [as handleEvent] (http://localhost:8100/build/vendor.js:13153:12)
    at dispatchEvent (http://localhost:8100/build/vendor.js:9173:21)
    at http://localhost:8100/build/vendor.js:9765:20
    at HTMLButtonElement.<anonymous> (http://localhost:8100/build/vendor.js:33938:53)
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:9967)
    at Object.onInvokeTask (http://localhost:8100/build/vendor.js:4499:37)`

**Comment by hariramsvnit** [comment]
@VigneshSAN Are you using `ionic serve` command to run the project? The SDK doesn't work with `ionic serve` command as mentioned in the doc(https://github.com/razorpay/razorpay-cordova#things-to-be-taken-care).

**Comment by bhushanjawle** [comment]
@VigneshSAN , try the following (this has worked for me)

1. Add browser platform with  `ionic cordova platform add browser` 

2. Test using `ionic run browser`

**Comment by ShaileshBhatNP** [comment]
Remember to add below lines to **_package.json_** file to clear the above bug

`"scripts": {`
   `"start": "ionic-app-scripts serve",`
    `"clean": "ionic-app-scripts clean",`
    `"build": "ionic-app-scripts build",`
    `"lint": "ionic-app-scripts lint",`
    `"ionic:build": "ionic-app-scripts build",`
    `"ionic:serve": "ionic-app-scripts serve --sourceMap source-map --iscordovaserve --wwwDir platforms/browser/www/ --buildDir platforms/browser/www/build"`
  `},`

**Comment by PrinceOfficial281995** [comment]
1. Add browser platform with ionic cordova platform add browser
2. Test using ionic cordova run  browser instead of  ionic run browser as it is old cmd.

**Comment by PrinceOfficial281995** [comment]
Add browser platform with **ionic cordova platform add browser**
Test using **ionic cordova run browser** instead of ionic run browser as it is old cmd.

**Comment by ersaurabh101** [comment]
but how do i make a browser build for it ?  should i use `ionic build --prod` ?  Please guide

**Comment by manojbharti** [comment]
I also have the same issue Razorpay not working in ionic build --prod. Please help

**Comment by daneshjamal** [comment]
I am also facing same issue. any update on this.

**Comment by 36Central** [comment]
> but how do i make a browser build for it ? should i use `ionic build --prod` ? Please guide

use `ionic cordova build browser --prod`
