### ISSUE TITLE
Using ionic versions  1 ,App crashing after  calling RazorpayCheckout.open

### ISSUE THREAD

**Issue by G-arun** [razorpay/razorpay-cordova-sample-app#14]
Hi,
After calling RazorpayCheckout.open app is  crashing .I installed plulgin using similar code in sample app like below
 $ionicPlatform.ready(function () {
        $scope.Rpay = function () {
            if (!called) {
              //  RazorpayCheckout.open(options, successCallback, cancelCallback);

                RazorpayCheckout.on('payment.success', successCallback)
                RazorpayCheckout.on('payment.cancel', cancelCallback)
                RazorpayCheckout.open(options)
                called = true
            }
        }
    });

Could you please tell what are things i need to cross check to resolve. As of now i am using test mode api key which is working in sample app

**Comment by G-arun** [comment]
I am able to resolve above crashing using live key  but we have issue that payment is stopped at razor pay activity ctrl not coming back to app even after adding document.addEventListener('resume', onResume, false); how on resume function in ionic v1 ?

**Comment by Mayur-Wadpalliwar** [comment]
Replied over ticket. Closing here.
