### ISSUE TITLE
Android Remember OTP verification is not working

### ISSUE THREAD

**Issue by dxmari** [razorpay/razorpay-cordova-sample-app#20]
I have used Cordova Razorpay plugin, I have a issue in reading a **OTP** in a remember cards section. The **OTP** is reading in a corresponding **Text Box** but its not working properly, it shows "**OTP is required**" in the next step. But I was typing the **OTP** text box **manually** it will be **working**, only **Auto Reading OTP** have a problem kindly **solve** this issue asap.

 Thanking You.

**Comment by dig22** [comment]
This behavior is expected as Android has stopped support permissions like READ_SMS for applications that are cannot be used as default Dialer or SMS applications.
