### ISSUE TITLE
Provide Sample app for Ionic 4 using angular

### ISSUE THREAD

**Issue by nagarajns** [razorpay/razorpay-cordova-sample-app#21]
Please Provide sample app for ionic 4 for subscription

**Comment by jagadishpvj** [comment]
yes i don't have declaration.d.ts while using angular with ionic 4..please provide if any other way to integrate in app modules

**Comment by siva563** [comment]
could u pls provide the ionic 4 with razorapy.

**Comment by sumedht** [comment]
Closing this issue as it's old & no further communication. U can re-open if it still need to be addressed
