### ISSUE TITLE
ionic build android (fails)

### ISSUE THREAD

**Issue by JasimJabri** [razorpay/razorpay-cordova-sample-app#4]
`ionic build android` fails.

To reproduce the error.

Please download the ionic 2 sample app from https://github.com/razorpay/razorpay-cordova-sample-app and run the following commands

`npm install`

`cd rzp-ionic2-example`

`mkdir www`

`cordova platform add android`

`ionic build android`

Please find below excerpt from the error message:

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileDebugJavaWithJavac'.
> Could not expand ZIP '/home/jaz/web/rzp-ionic2-example/platforms/android/build/intermediates/exploded-aar/com.razorpay/checkout/1.2.0/jars/classes.jar'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 2 mins 49.599 secs

Error: /home/jaz/web/rzp-ionic2-example/platforms/android/gradlew: Command failed with exit code 1 Error output:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileDebugJavaWithJavac'.
> Could not expand ZIP '/home/jaz/web/rzp-ionic2-example/platforms/android/build/intermediates/exploded-aar/com.razorpay/checkout/1.2.0/jars/classes.jar'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

**Comment by mb-14** [comment]
@JasimJabri  We were unable to reproduce this issue on our end. Can you run the build command with the `stacktrace` flag. You need to run the following commands:

```
cd platforms/android
./gradlew assembleDefault --stacktrace 
```
