### ISSUE TITLE
Provide sample app for Ionic 5 + React

### ISSUE THREAD

**Issue by webacers** [razorpay/razorpay-cordova-sample-app#51]
Hi, 
Please provide sample app for Ionic 5+React+ Capacitor. 

Thanks

**Comment by shoaibakhter2007** [comment]
Hi,

I am also looking for a sample code for Ionic React with capacitor as Cordova is not supported by Ionic with React. 

Thanks

**Comment by sumedht** [comment]
@webacers @shoaibakhter2007 U can find capacitor plugin from [here](https://github.com/razorpay/razorpay-capacitor)
